In [54]:
import pandas as pd
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
import collections

In [55]:
pd.set_option('display.max_rows', 20)

In [60]:
df = pd.read_csv("./raw_data/metadata.tsv", sep="\t")
# Filter by conditions
df = df[(df["host"] == 'Human') & (df["age"] != "?") & ((df["sex"] == "Male") | (df["sex"] == "Female"))]
# Only want a few columns
df = df[['gisaid_epi_isl', "country", "age", "sex", "date_submitted"]]
# Preview
df

,gisaid_epi_isl,country,age,sex,date_submitted
0,EPI_ISL_418241,Algeria,28,Female,2020-03-29
1,EPI_ISL_418242,Algeria,87,Male,2020-03-29
2,EPI_ISL_420037,Algeria,41,Male,2020-04-04
3,EPI_ISL_413485,China,58,Male,2020-03-05
4,EPI_ISL_420600,Argentina,51,Male,2020-04-06
5,EPI_ISL_420599,Argentina,47,Male,2020-04-06
6,EPI_ISL_420598,Argentina,73,Male,2020-04-06
7,EPI_ISL_430793,Argentina,40,Male,2020-04-27
8,EPI_ISL_430794,Argentina,40,Male,2020-04-27
9,EPI_ISL_430795,Argentina,57,Female,2020-04-27
...,...,...,...,...,...
16198,EPI_ISL_421260,China,42,Female,2020-04-07
16199,EPI_ISL_429239,China,16,Female,2020-04-23
16200,EPI_ISL_408480,China,56,Male,2020-02-09
16201,EPI_ISL_422425,China,36,Male,2020-04-10
16202,EPI_ISL_404227,China,46,Male,2020-01-21
16203,EPI_ISL_404228,China,47,Male,2020-01-21
16219,EPI_ISL_434710,Democratic Republic of the Congo,37,Male,2020-05-01
16220,EPI_ISL_435286,Israel,55,Female,2020-05-04
16221,EPI_ISL_435289,Israel,41,Female,2020-05-04
16222,EPI_ISL_435292,Israel,61,Female,2020-05-04

In [57]:
data_set = collections.defaultdict(list)
for i, (gisaid, *rest) in df.iterrows():
    # rest = (country, age, sex, date), in that order
    data_set[gisaid].extend(rest) 
# Example of dataset:
for i, val in enumerate(data_set.items()):
    print(val)
    if i == 10: break

('EPI_ISL_418241', ['Algeria', '28', 'Female', '2020-03-29'])
('EPI_ISL_418242', ['Algeria', '87', 'Male', '2020-03-29'])
('EPI_ISL_420037', ['Algeria', '41', 'Male', '2020-04-04'])
('EPI_ISL_413485', ['China', '58', 'Male', '2020-03-05'])
('EPI_ISL_420600', ['Argentina', '51', 'Male', '2020-04-06'])
('EPI_ISL_420599', ['Argentina', '47', 'Male', '2020-04-06'])
('EPI_ISL_420598', ['Argentina', '73', 'Male', '2020-04-06'])
('EPI_ISL_430793', ['Argentina', '40', 'Male', '2020-04-27'])
('EPI_ISL_430794', ['Argentina', '40', 'Male', '2020-04-27'])
('EPI_ISL_430795', ['Argentina', '57', 'Female', '2020-04-27'])
('EPI_ISL_430796', ['Argentina', '30', 'Male', '2020-04-27'])

### Filter faster file based those available in data_set

In [58]:
records = []
for i, record in enumerate(SeqIO.parse("D:\gisaid_hcov-19_2020_05_14_18.fasta", "fasta")):
    header = record.id.split("|")
    if len(header) > 1 and header[1] in data_set:
        records.append(record)

### Save new fasta file

In [59]:
SeqIO.write(records, "./data/gisaid_cov2020_sequences_filtered.fasta", "fasta")

8312